---
koku:
    # this is how you would configure quipucords if running
    # the development server
    # if running in a container, set the port to 443
    # and https to true. Keep ssl-verify false unless you've
    # set up the certificates
    hostname: '127.0.0.1'
    https: false
    port: 8000
    ssl-verify: false
    # credentials for logging into the server
    username: 'admin'
    password: 'pass'
